import '../final_select_upcycle_screen/widgets/frame15_item_widget.dart';import '../final_select_upcycle_screen/widgets/frame16_item_widget.dart';import 'controller/final_select_upcycle_controller.dart';import 'models/frame15_item_model.dart';import 'models/frame16_item_model.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_three.dart';import 'package:mykanji/widgets/app_bar/appbar_trailing_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_drop_down.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_outlined_button.dart';import 'package:mykanji/widgets/custom_text_form_field.dart';class FinalSelectUpcycleScreen extends GetWidget<FinalSelectUpcycleController> {const FinalSelectUpcycleScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: Padding(padding: EdgeInsets.only(bottom: 10.v), child: Column(children: [_buildServiceProvider(), SizedBox(height: 32.v), _buildServiceSelected(), SizedBox(height: 35.v), _buildSelectClothing(), SizedBox(height: 19.v), _buildBlouseType(), SizedBox(height: 34.v), _buildStyleDescription(), SizedBox(height: 16.v), _buildUploadReference(), _buildSelectAddOn(), _buildEstimatedPrice(), _buildSelectMeasurements(), _buildFinalSelectUpcycle(), SizedBox(height: 17.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray50, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleThree(text: "msg_fill_order_details".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgNotificationGray5001, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))], styleType: Style.bgFill_2); } 
/// Section Widget
Widget _buildServiceProvider() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_provider2".tr, style: theme.textTheme.titleLarge), SizedBox(height: 8.v), Container(decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgFrame, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(4.h)), Padding(padding: EdgeInsets.only(left: 8.h, top: 10.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_provider".tr, style: CustomTextStyles.titleMediumGray90002), SizedBox(height: 7.v), SizedBox(width: 237.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_rating_4_3".tr, style: CustomTextStyles.bodyMedium_1), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.gray700, endIndent: 2.h)), Text("msg_price_range_250_550".tr, style: CustomTextStyles.bodyMedium_1)]))]))]))])); } 
/// Section Widget
Widget _buildServiceSelected() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_selected".tr, style: theme.textTheme.titleLarge), SizedBox(height: 16.v), CustomTextFormField(controller: controller.textFieldController, hintText: "lbl_stitching".tr, hintStyle: CustomTextStyles.bodyLargeGray800, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false)])); } 
/// Section Widget
Widget _buildSelectClothing() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_select_clothing".tr, style: theme.textTheme.titleLarge), SizedBox(height: 14.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_blouse".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.finalSelectUpcycleModelObj.value.dropdownItemList.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildBlouseType() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_blouse_type".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "msg_cut_blouses_1500".tr, hintStyle: CustomTextStyles.bodyLargeGray900, items: controller.finalSelectUpcycleModelObj.value.dropdownItemList1.value, onChanged: (value) {controller.onSelected1(value);})])); } 
/// Section Widget
Widget _buildStyleDescription() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_style_description".tr, style: theme.textTheme.titleLarge), SizedBox(height: 14.v), CustomTextFormField(controller: controller.descriptionController, hintText: "msg_take_your_design".tr, hintStyle: CustomTextStyles.bodyLargeCabinGray800, maxLines: 4, borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false)])); } 
/// Section Widget
Widget _buildThumbnail1() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_upload_reference".tr, style: theme.textTheme.titleLarge), SizedBox(height: 14.v), SizedBox(height: 161.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: controller.finalSelectUpcycleModelObj.value.frame15ItemList.value.length, itemBuilder: (context, index) {Frame15ItemModel model = controller.finalSelectUpcycleModelObj.value.frame15ItemList.value[index]; return Frame15ItemWidget(model);})))]); } 
/// Section Widget
Widget _buildThumbnail2() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_upload_material".tr, style: theme.textTheme.titleLarge), SizedBox(height: 13.v), SizedBox(height: 161.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: controller.finalSelectUpcycleModelObj.value.frame16ItemList.value.length, itemBuilder: (context, index) {Frame16ItemModel model = controller.finalSelectUpcycleModelObj.value.frame16ItemList.value[index]; return Frame16ItemWidget(model);})))]); } 
/// Section Widget
Widget _buildUploadReference() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), _buildThumbnail1(), SizedBox(height: 16.v), _buildThumbnail2()])); } 
/// Section Widget
Widget _buildSelectAddOn() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_select_add_on".tr, style: theme.textTheme.titleLarge), SizedBox(height: 16.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.finalSelectUpcycleModelObj.value.dropdownItemList2.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected2(value);})])); } 
/// Section Widget
Widget _buildEstimatedPrice() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_estimated_price".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), CustomTextFormField(controller: controller.priceController, hintText: "lbl_2_500".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false)])); } 
/// Section Widget
Widget _buildSelectMeasurements() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_select_measurements".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_measurements_1".tr, items: controller.finalSelectUpcycleModelObj.value.dropdownItemList3.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected3(value);})])); } 
/// Section Widget
Widget _buildFinalSelectUpcycle() { return Container(padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 16.v), decoration: AppDecoration.fillGray5001, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(width: 173.h, text: "lbl_save_add_more".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgPlus, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.outlineDeepPurple), CustomElevatedButton(width: 157.h, text: "lbl_confirm_quote".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray50, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.fillDeepPurple)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
