import 'controller/help_and_support_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';class HelpAndSupportScreen extends GetWidget<HelpAndSupportController> {const HelpAndSupportScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: 412.h, child: Container(padding: EdgeInsets.symmetric(vertical: 10.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAppBar(), SizedBox(height: 24.v), _buildFrameRowOne(), SizedBox(height: 24.v), _buildFrameRowTwo(), SizedBox(height: 24.v), GestureDetector(onTap: () {onTapFrame();}, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMaterialSymbol, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, bottom: 2.v), child: Text("lbl_feedback".tr, style: CustomTextStyles.bodyLargeSFProGray90005))]))), SizedBox(height: 24.v), GestureDetector(onTap: () {onTapFrame1();}, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgIcOutlineInfo, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, bottom: 2.v), child: Text("lbl_about_us".tr, style: CustomTextStyles.bodyLargeSFProGray90005))]))), Spacer(), Align(alignment: Alignment.center, child: SizedBox(width: 108.h, child: Divider()))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "msg_help_and_support".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildFrameRowOne() { return Padding(padding: EdgeInsets.only(left: 16.h, right: 59.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgIcOutlineMail, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_for_support_mail2".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_mykanjee_gmail_com".tr, style: CustomTextStyles.bodyLargeSFProLightblueA700)]), textAlign: TextAlign.left))])); } 
/// Section Widget
Widget _buildFrameRowTwo() { return Padding(padding: EdgeInsets.only(left: 16.h, right: 51.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgCall, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_for_any_queries2".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "lbl_080_8724_6758".tr, style: CustomTextStyles.bodyLargeSFProLightblueA700)]), textAlign: TextAlign.left))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the feedbackScreen when the action is triggered.
onTapFrame() { Get.toNamed(AppRoutes.feedbackScreen, ); } 
/// Navigates to the aboutUsScreen when the action is triggered.
onTapFrame1() { Get.toNamed(AppRoutes.aboutUsScreen, ); } 
 }
