import 'controller/providersproduct_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_icon_button.dart';import 'package:mykanji/widgets/custom_search_view.dart';class ProvidersproductScreen extends GetWidget<ProvidersproductController> {const ProvidersproductScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: Padding(padding: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 10.v), child: Column(children: [_buildSearchRow(), SizedBox(height: 16.v), _buildStackedCardRow(), SizedBox(height: 8.v), _buildStackedCardRow1(), SizedBox(height: 8.v), _buildAdd6(), SizedBox(height: 30.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "lbl_products".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildSearchRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomSearchView(controller: controller.searchController, hintText: "msg_hinted_search_text".tr)), Padding(padding: EdgeInsets.only(left: 16.h), child: CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.fillOnErrorContainer, child: CustomImageView(imagePath: ImageConstant.imgSearch)))]); } 
/// Section Widget
Widget _buildAdd() { return CustomElevatedButton(height: 33.v, width: 104.h, text: "lbl_add".tr, buttonTextStyle: CustomTextStyles.titleMediumSFProBluegray700, alignment: Alignment.bottomCenter); } 
/// Section Widget
Widget _buildAdd1() { return CustomElevatedButton(height: 33.v, width: 104.h, text: "lbl_add".tr, buttonTextStyle: CustomTextStyles.titleMediumSFProBluegray700, alignment: Alignment.bottomCenter); } 
/// Section Widget
Widget _buildStackedCardRow() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 4.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 198.v, width: 186.h, child: Stack(alignment: Alignment.bottomCenter, children: [_buildMedia(), _buildAdd()])), SizedBox(height: 2.v), _buildHeadlineColumn(sareesCount: "lbl_zari_pure_silk".tr, price: "lbl_3_500".tr), SizedBox(height: 16.v)]))), Expanded(child: Container(margin: EdgeInsets.only(left: 4.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 198.v, width: 186.h, child: Stack(alignment: Alignment.bottomCenter, children: [_buildMedia(), _buildAdd1()])), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_sarees_2".tr, style: CustomTextStyles.bodyLargeCabinGray900)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_3_500".tr, style: CustomTextStyles.bodyMediumGray800)), SizedBox(height: 16.v)])))]); } 
/// Section Widget
Widget _buildAdd2() { return CustomElevatedButton(height: 33.v, width: 104.h, text: "lbl_add".tr, buttonTextStyle: CustomTextStyles.titleMediumSFProBluegray700, alignment: Alignment.bottomCenter); } 
/// Section Widget
Widget _buildAdd3() { return CustomElevatedButton(height: 33.v, width: 104.h, text: "lbl_add".tr, buttonTextStyle: CustomTextStyles.titleMediumSFProBluegray700, alignment: Alignment.center); } 
/// Section Widget
Widget _buildStackedCardRow1() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 198.v, width: 186.h, child: Stack(alignment: Alignment.bottomCenter, children: [_buildMedia(), _buildAdd2()])), SizedBox(height: 2.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_sarees_3".tr, style: CustomTextStyles.bodyLargeCabinGray900)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_3_500".tr, style: CustomTextStyles.bodyMediumGray800)), SizedBox(height: 16.v)])), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.gray300, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder12), child: Container(height: 258.v, width: 186.h, decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMedia182x182, height: 182.v, width: 186.h, alignment: Alignment.topCenter), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(8.h), alignment: Alignment.centerRight, child: CustomImageView(imagePath: ImageConstant.imgWishlistPro)), SizedBox(height: 113.v), _buildAdd3(), SizedBox(height: 2.v), Text("lbl_sarees_4".tr, style: CustomTextStyles.bodyLargeCabinGray900), SizedBox(height: 3.v), Text("lbl_3_500".tr, style: CustomTextStyles.bodyMediumGray800)])))])))]); } 
/// Section Widget
Widget _buildAdd4() { return CustomElevatedButton(height: 33.v, width: 104.h, text: "lbl_add".tr, buttonTextStyle: CustomTextStyles.titleMediumSFProBluegray700, alignment: Alignment.bottomCenter); } 
/// Section Widget
Widget _buildAdd5() { return CustomElevatedButton(height: 33.v, width: 104.h, text: "lbl_add".tr, buttonTextStyle: CustomTextStyles.titleMediumSFProBluegray700, alignment: Alignment.center); } 
/// Section Widget
Widget _buildAdd6() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 198.v, width: 186.h, child: Stack(alignment: Alignment.bottomCenter, children: [_buildMedia(), _buildAdd4()])), SizedBox(height: 2.v), _buildHeadlineColumn(sareesCount: "lbl_sarees_5".tr, price: "lbl_3_500".tr), SizedBox(height: 16.v)])), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.gray300, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder12), child: Container(height: 258.v, width: 186.h, decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgMedia182x182, height: 182.v, width: 186.h, alignment: Alignment.topCenter), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(8.h), alignment: Alignment.centerRight, child: CustomImageView(imagePath: ImageConstant.imgWishlistPro)), SizedBox(height: 113.v), _buildAdd5(), SizedBox(height: 2.v), Text("lbl_sarees_6".tr, style: CustomTextStyles.bodyLargeCabinGray900), SizedBox(height: 3.v), Text("lbl_3_500".tr, style: CustomTextStyles.bodyMediumGray800)])))])))]); } 
/// Common widget
Widget _buildMedia() { return SizedBox(height: 182.v, width: 186.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgMedia182x182, height: 182.v, width: 186.h, alignment: Alignment.center), Padding(padding: EdgeInsets.only(top: 16.v, right: 16.h), child: CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(8.h), alignment: Alignment.topRight, child: CustomImageView(imagePath: ImageConstant.imgWishlistPro)))])); } 
/// Common widget
Widget _buildHeadlineColumn({required String sareesCount, required String price, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(sareesCount, style: CustomTextStyles.bodyLargeCabinGray900.copyWith(color: appTheme.gray900)), SizedBox(height: 3.v), Text(price, style: CustomTextStyles.bodyMediumGray800.copyWith(color: appTheme.gray800))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
