import '../service_provider_listing_screen/widgets/listviewlist_item_widget.dart';import 'controller/service_provider_listing_controller.dart';import 'models/listviewlist_item_model.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/presentation/productscreen_container_page/productscreen_container_page.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/appbar_trailing_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_bottom_bar.dart';class ServiceProviderListingScreen extends GetWidget<ServiceProviderListingController> {const ServiceProviderListingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: 412.h, child: Column(children: [SizedBox(height: 16.v), Expanded(child: SingleChildScrollView(child: Column(children: [_buildFrame(), SizedBox(height: 16.v), _buildFrame1(), SizedBox(height: 16.v), _buildListviewList()])))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgLinkedin, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v)), title: AppbarSubtitleFour(text: "lbl_koramangala".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgSearchBlack900, margin: EdgeInsets.only(left: 16.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgNotification, margin: EdgeInsets.only(left: 28.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgLock, margin: EdgeInsets.only(left: 28.h, top: 20.v, right: 36.h))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFrame() { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildFilterChip(leadingIcon: ImageConstant.imgCheckmark, popular: "lbl_nearest".tr), Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 5.v), decoration: AppDecoration.outlineGray6001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_rating_4_0".tr, style: CustomTextStyles.titleSmallGray800))]))), _buildFilterChip(leadingIcon: ImageConstant.imgLeadingIcon, popular: "lbl_popular".tr)])); } 
/// Section Widget
Widget _buildFrame1() { return SizedBox(height: 20.v, width: 380.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 380.h, child: Divider(color: appTheme.gray90002))), Align(alignment: Alignment.center, child: Container(width: 187.h, padding: EdgeInsets.symmetric(horizontal: 8.h), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("msg_42_upcycle_services".tr, style: CustomTextStyles.bodyMedium_1)))])); } 
/// Section Widget
Widget _buildListviewList() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.fillGray5001, child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.serviceProviderListingModelObj.value.listviewlistItemList.value.length, itemBuilder: (context, index) {ListviewlistItemModel model = controller.serviceProviderListingModelObj.value.listviewlistItemList.value[index]; return ListviewlistItemWidget(model);}))); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildFilterChip({required String leadingIcon, required String popular, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 5.v), decoration: AppDecoration.outlineGray6001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: leadingIcon, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text(popular, style: CustomTextStyles.titleSmallGray800.copyWith(color: appTheme.gray800)))]))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.productscreenContainerPage; case BottomBarEnum.Quote: return "/"; case BottomBarEnum.Orders: return "/"; case BottomBarEnum.Replies: return "/"; case BottomBarEnum.Cart: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.productscreenContainerPage: return ProductscreenContainerPage(); default: return DefaultWidget();} } 
 }
