import 'controller/login_and_security_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_text_form_field.dart';class LoginAndSecurityScreen extends GetWidget<LoginAndSecurityController> {const LoginAndSecurityScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: 412.h, child: Container(padding: EdgeInsets.symmetric(vertical: 10.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 24.v), _buildAccountDetails(), SizedBox(height: 17.v), _buildAccountNumber(), SizedBox(height: 17.v), _buildBankName(), SizedBox(height: 25.v), _buildCity(), SizedBox(height: 24.v), _buildBranch(), SizedBox(height: 24.v), _buildIfscCode(), Spacer(), SizedBox(width: 108.h, child: Divider())]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "lbl_account_details".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildAccountDetails() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_account_holder_name".tr, style: theme.textTheme.bodySmall), SizedBox(height: 10.v), CustomTextFormField(controller: controller.nameController, hintText: "lbl_enter_here".tr, hintStyle: CustomTextStyles.bodyLargeSFProPrimaryContainer_1, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)])); } 
/// Section Widget
Widget _buildAccountNumber() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_account_number".tr, style: theme.textTheme.bodySmall), SizedBox(height: 10.v), CustomTextFormField(controller: controller.iFSCCodevalueController, hintText: "lbl_enter_here".tr, hintStyle: CustomTextStyles.bodyLargeSFProPrimaryContainer_1, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)])); } 
/// Section Widget
Widget _buildBankName() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_bank_name".tr, style: theme.textTheme.bodySmall), SizedBox(height: 10.v), Container(padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 9.v), decoration: AppDecoration.outlineGray90005.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_select_here".tr, style: CustomTextStyles.bodyLargeSFProPrimaryContainer_1)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.symmetric(vertical: 3.v))]))])); } 
/// Section Widget
Widget _buildCity() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: theme.textTheme.bodySmall), SizedBox(height: 9.v), CustomTextFormField(controller: controller.cityController, hintText: "lbl_enter_here".tr, hintStyle: CustomTextStyles.bodyLargeSFProPrimaryContainer_1, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)])); } 
/// Section Widget
Widget _buildBranch() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_branch".tr, style: theme.textTheme.bodySmall), SizedBox(height: 10.v), CustomTextFormField(controller: controller.iFSCCodevalueController1, hintText: "lbl_enter_here".tr, hintStyle: CustomTextStyles.bodyLargeSFProPrimaryContainer_1, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)])); } 
/// Section Widget
Widget _buildIfscCode() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_ifsc_code".tr, style: theme.textTheme.bodySmall), SizedBox(height: 10.v), CustomTextFormField(controller: controller.iFSCCodevalueController2, hintText: "lbl_enter_here".tr, hintStyle: CustomTextStyles.bodyLargeSFProPrimaryContainer_1, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
