import '../final_restore_screen/widgets/frame17_item_widget.dart';import 'controller/final_restore_controller.dart';import 'models/frame17_item_model.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_drop_down.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_outlined_button.dart';import 'package:mykanji/widgets/custom_text_form_field.dart';class FinalRestoreScreen extends GetWidget<FinalRestoreController> {const FinalRestoreScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 10.v), child: Column(children: [_buildServiceProvider(), _buildServiceSelected(), _buildSelectClothing(), _buildAdditionalInstructions(), _buildUploadMaterial(), _buildSelectAddOn(), _buildEstimatedPrice(), _buildFinalRestore(), SizedBox(height: 37.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 412.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.fromLTRB(16.h, 20.v, 372.h, 20.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgFill_3); } 
/// Section Widget
Widget _buildServiceProvider() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_service_provider2".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Container(decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgFrame, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(4.h)), Padding(padding: EdgeInsets.only(left: 8.h, top: 10.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_provider".tr, style: CustomTextStyles.titleMediumGray90002), SizedBox(height: 7.v), SizedBox(width: 237.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_rating_4_3".tr, style: CustomTextStyles.bodyMedium_1), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.gray700, endIndent: 2.h)), Text("msg_price_range_250_550".tr, style: CustomTextStyles.bodyMedium_1)]))]))]))])); } 
/// Section Widget
Widget _buildTextField() { return CustomTextFormField(controller: controller.textFieldController, hintText: "lbl_stain_removal".tr, hintStyle: CustomTextStyles.bodyMediumGray800, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), borderDecoration: TextFormFieldStyleHelper.fillGrayTL4, fillColor: appTheme.gray100); } 
/// Section Widget
Widget _buildServiceSelected() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_service_selected".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), _buildTextField()])); } 
/// Section Widget
Widget _buildIcon() { return CustomTextFormField(controller: controller.iconController, hintText: "lbl_kanjeevaram".tr, hintStyle: CustomTextStyles.bodyLargeGray900, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 14.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgCloseGray80001, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(left: 16.h, top: 18.v, bottom: 18.v)); } 
/// Section Widget
Widget _buildSelectClothing() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Text("msg_select_clothing".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), _buildIcon()])); } 
/// Section Widget
Widget _buildDescription() { return CustomTextFormField(controller: controller.descriptionController, hintText: "msg_take_your_design".tr, hintStyle: CustomTextStyles.bodyLargeCabinGray800, maxLines: 4, contentPadding: EdgeInsets.symmetric(horizontal: 2.h, vertical: 10.v), borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false); } 
/// Section Widget
Widget _buildAdditionalInstructions() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_additional_instructions".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), _buildDescription()])); } 
/// Section Widget
Widget _buildUploadMaterial() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("msg_upload_material".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), SizedBox(height: 161.v, child: Obx(() => ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: controller.finalRestoreModelObj.value.frame17ItemList.value.length, itemBuilder: (context, index) {Frame17ItemModel model = controller.finalRestoreModelObj.value.frame17ItemList.value[index]; return Frame17ItemWidget(model);})))])); } 
/// Section Widget
Widget _buildSelectAddOn() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_select_add_on".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.finalRestoreModelObj.value.dropdownItemList.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildPrice() { return CustomTextFormField(controller: controller.priceController, hintText: "lbl_2_500".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL41, fillColor: appTheme.gray100); } 
/// Section Widget
Widget _buildEstimatedPrice() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_estimated_price".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), _buildPrice()])); } 
/// Section Widget
Widget _buildAddMoreService() { return Expanded(child: CustomOutlinedButton(text: "msg_add_more_service".tr, margin: EdgeInsets.only(right: 5.h), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgPlusBlack900, height: 18.adaptSize, width: 18.adaptSize)))); } 
/// Section Widget
Widget _buildGetAQuote() { return Expanded(child: CustomElevatedButton(text: "lbl_get_a_quote".tr, margin: EdgeInsets.only(left: 5.h), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray50, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.fillBlueGray)); } 
/// Section Widget
Widget _buildFinalRestore() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v), decoration: AppDecoration.fillGray5001, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildAddMoreService(), _buildGetAQuote()])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
