import 'controller/stain_removel_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_trailing_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_drop_down.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_text_form_field.dart';class StainRemovelScreen extends GetWidget<StainRemovelController> {const StainRemovelScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 18.v), child: Padding(padding: EdgeInsets.only(bottom: 10.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_service_provider2".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 9.v), _buildServiceProviderRow(), SizedBox(height: 34.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_service_selected".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 9.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: CustomTextFormField(controller: controller.serviceSelectedvalueController, hintText: "lbl_stain_removal".tr, hintStyle: CustomTextStyles.bodyMediumGray800, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), borderDecoration: TextFormFieldStyleHelper.fillGrayTL4, fillColor: appTheme.gray100)), SizedBox(height: 34.v), _buildSelectMaterialColumn(), SizedBox(height: 34.v), _buildAdditionalInstructionsColumn(), SizedBox(height: 16.v), _buildUploadItemPhotosColumn(), _buildSelectAddOnColumn(), _buildRequestQuotationColumn(), SizedBox(height: 72.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgNotificationBlack900, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildServiceProviderRow() { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgFrame, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(4.h)), Padding(padding: EdgeInsets.only(left: 8.h, top: 11.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_sultan_dry_cleaner".tr, style: CustomTextStyles.titleMediumGray90002), SizedBox(height: 6.v), SizedBox(width: 237.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_rating_4_3".tr, style: CustomTextStyles.bodyMedium_1), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.gray700, endIndent: 2.h)), Text("msg_price_range_250_550".tr, style: CustomTextStyles.bodyMedium_1)]))]))])); } 
/// Section Widget
Widget _buildSelectMaterialColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_select_material".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.stainRemovelModelObj.value.dropdownItemList.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildAdditionalInstructionsColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_additional_instructions".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomTextFormField(controller: controller.textFieldController, hintText: "lbl_label".tr, hintStyle: CustomTextStyles.bodyLargeGray800, textInputAction: TextInputAction.done, maxLines: 5, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false)])); } 
/// Section Widget
Widget _buildUploadItemPhotosColumn() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("msg_upload_item_photos".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 8.h), child: _buildUploadImagesColumn(uploadImages: "lbl_upload_images".tr, onTapStateLayer: () {onTapStateLayer();})), Padding(padding: EdgeInsets.only(left: 8.h), child: _buildUploadImagesColumn(uploadImages: "lbl_upload_images".tr))])])); } 
/// Section Widget
Widget _buildSelectAddOnColumn() { return Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_select_add_on".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.stainRemovelModelObj.value.dropdownItemList1.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected1(value);})])); } 
/// Section Widget
Widget _buildRequestQuotationColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 113.h, vertical: 16.v), decoration: AppDecoration.fillGray5001, child: CustomElevatedButton(text: "msg_request_quotation".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray50, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.fillGrayTL81, buttonTextStyle: CustomTextStyles.titleSmallGray900_1)); } 
/// Common widget
Widget _buildUploadImagesColumn({required String uploadImages, Function? onTapStateLayer, }) { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 11.v), decoration: AppDecoration.fillDeeppurple50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: GestureDetector(onTap: () {onTapStateLayer!.call();}, child: Container(decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgIconsFileupload, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v), child: Text(uploadImages, style: CustomTextStyles.labelLargeCabinGray90002.copyWith(color: appTheme.gray90002)))])))))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the restoreUploadScreen when the action is triggered.
onTapStateLayer() { Get.toNamed(AppRoutes.restoreUploadScreen, ); } 
 }
