import 'controller/privacy_policy_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_one.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';class PrivacyPolicyScreen extends GetWidget<PrivacyPolicyController> {const PrivacyPolicyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: appTheme.gray5001, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 18.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 10.v), child: Column(children: [SizedBox(width: 364.h, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_thank_you_for_using2".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_1_information_collection".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_we_collect_information".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_2_use_of_information".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_we_use_your_information".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_3_data_security".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_we_implement_security".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_4_third_party_services".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_we_may_use_third_party".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_5_cookies_and_tracking".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_we_use_cookies_and".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_6_user_content".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_content_you_share".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_7_children_s_privacy".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_the_platform_is".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_8_your_choices".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_you_can_update_your".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_9_changes_to_privacy".tr, style: CustomTextStyles.titleMediumSFProGray90005), TextSpan(text: "msg_we_may_update_this".tr, style: CustomTextStyles.bodyLargeSFProGray90005_1), TextSpan(text: "msg_10_contact_us".tr, style: CustomTextStyles.titleMediumSFProGray90005)]), textAlign: TextAlign.left)), SizedBox(height: 53.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_privacy_policy".tr), styleType: Style.bgFill_1); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
