import '../input_form_screen/widgets/frame3_item_widget.dart';import '../input_form_screen/widgets/frame5_item_widget.dart';import 'controller/input_form_controller.dart';import 'models/frame3_item_model.dart';import 'models/frame5_item_model.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/appbar_trailing_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_drop_down.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_text_form_field.dart';class InputFormScreen extends GetWidget<InputFormController> {const InputFormScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 18.v), child: Padding(padding: EdgeInsets.only(bottom: 10.v), child: Column(children: [_buildServiceProvider(), SizedBox(height: 34.v), _buildStitchingValue(), SizedBox(height: 36.v), _buildSelectClothing(), SizedBox(height: 35.v), _buildStyleDescription(), SizedBox(height: 16.v), _buildUploadSection(), SizedBox(height: 18.v), _buildRequestQuotation(), SizedBox(height: 8.v), _buildSelectMeasurements(), SizedBox(height: 20.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "msg_fill_order_detail".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgLockGray800, margin: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildServiceProvider() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_provider2".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Container(decoration: AppDecoration.outlineBlack9001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgFrame, height: 64.adaptSize, width: 64.adaptSize, radius: BorderRadius.circular(4.h)), Padding(padding: EdgeInsets.only(left: 8.h, top: 10.v, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_provider".tr, style: CustomTextStyles.titleMediumGray90002), SizedBox(height: 7.v), SizedBox(width: 237.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_rating_4_3".tr, style: CustomTextStyles.bodyMedium_1), SizedBox(height: 18.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.gray700, endIndent: 2.h)), Text("msg_price_range_250_550".tr, style: CustomTextStyles.bodyMedium_1)]))]))]))])); } 
/// Section Widget
Widget _buildStitchingValue() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_selected".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), CustomTextFormField(controller: controller.stitchingvalueController, hintText: "lbl_stitching".tr, hintStyle: CustomTextStyles.bodyLargeGray800, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineOnPrimary, fillColor: appTheme.gray100)])); } 
/// Section Widget
Widget _buildSelectClothing() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_select_clothing".tr, style: theme.textTheme.titleMedium), SizedBox(height: 7.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.inputFormModelObj.value.dropdownItemList.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected(value);})])); } 
/// Section Widget
Widget _buildStyleDescription() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_style_description".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), CustomTextFormField(controller: controller.labelvalueController, hintText: "lbl_label".tr, hintStyle: CustomTextStyles.bodyLargeGray800, textInputAction: TextInputAction.done, maxLines: 5, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 17.v), borderDecoration: TextFormFieldStyleHelper.outlineGray, filled: false)])); } 
/// Section Widget
Widget _buildReferenceImages() { return Padding(padding: EdgeInsets.only(right: 64.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_upload_reference".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), Obx(() => Wrap(runSpacing: 16.v, spacing: 16.h, children: List<Widget>.generate(controller.inputFormModelObj.value.frame3ItemList.value.length, (index) {Frame3ItemModel model = controller.inputFormModelObj.value.frame3ItemList.value[index]; return Frame3ItemWidget(model);})))])); } 
/// Section Widget
Widget _buildMaterialImages() { return Padding(padding: EdgeInsets.only(right: 64.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_upload_material".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Obx(() => Wrap(runSpacing: 16.v, spacing: 16.h, children: List<Widget>.generate(controller.inputFormModelObj.value.frame5ItemList.value.length, (index) {Frame5ItemModel model = controller.inputFormModelObj.value.frame5ItemList.value[index]; return Frame5ItemWidget(model);})))])); } 
/// Section Widget
Widget _buildUploadSection() { return Container(width: 412.h, padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), _buildReferenceImages(), SizedBox(height: 27.v), _buildMaterialImages()])); } 
/// Section Widget
Widget _buildRequestQuotation() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_select_add_on".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 9.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.inputFormModelObj.value.dropdownItemList1.value, borderDecoration: DropDownStyleHelper.outlineGray, filled: false, onChanged: (value) {controller.onSelected1(value);}), SizedBox(height: 24.v), CustomElevatedButton(width: 185.h, text: "msg_request_quotation".tr, leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray50, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.fillGrayTL81, buttonTextStyle: CustomTextStyles.titleSmallGray900_1)])); } 
/// Section Widget
Widget _buildSelectMeasurements() { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillGray5001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_select_measurements".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgIconsArrowdropdown24px, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_select_item".tr, hintStyle: CustomTextStyles.bodyLargeGray800, items: controller.inputFormModelObj.value.dropdownItemList2.value, prefix: Container(margin: EdgeInsets.symmetric(horizontal: 12.h, vertical: 16.v), child: CustomImageView(imagePath: ImageConstant.imgSearchGray80001, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.symmetric(vertical: 18.v), onChanged: (value) {controller.onSelected2(value);})])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
