import '../payment_screen/widgets/listitemlistitem_item_widget.dart';import 'controller/payment_controller.dart';import 'models/listitemlistitem_item_model.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';class PaymentScreen extends GetWidget<PaymentController> {const PaymentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: 412.h, child: Container(padding: EdgeInsets.symmetric(vertical: 10.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder18), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 24.v), _buildListItem(), SizedBox(height: 27.v), _buildFrame(), SizedBox(height: 426.v), SizedBox(width: 108.h, child: Divider())]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "lbl_payments".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildListItem() { return Container(width: 364.h, margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.fillDeeppurple50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_available_balance".tr, style: CustomTextStyles.titleMediumGray90002), SizedBox(height: 2.v), Text("lbl_price_2_000".tr, style: CustomTextStyles.bodyMediumGray700_1)])); } 
/// Section Widget
Widget _buildFrame() { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Text("lbl_past_payouts".tr, style: theme.textTheme.titleLarge), SizedBox(height: 13.v), Expanded(child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.paymentModelObj.value.listitemlistitemItemList.value.length, itemBuilder: (context, index) {ListitemlistitemItemModel model = controller.paymentModelObj.value.listitemlistitemItemList.value[index]; return ListitemlistitemItemWidget(model);})))])))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
