import 'controller/upper_body_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/presentation/lower_body_page/lower_body_page.dart';import 'package:mykanji/presentation/upper_body_page/upper_body_page.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_one.dart';import 'package:mykanji/widgets/app_bar/appbar_trailing_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';class UpperBodyTabContainerScreen extends GetWidget<UpperBodyTabContainerController> {const UpperBodyTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: Column(children: [_buildTabview(), SizedBox(height: 1200.v, child: TabBarView(controller: controller.tabviewController, children: [UpperBodyPage(), UpperBodyPage(), LowerBodyPage()]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 36.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 12.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), title: AppbarSubtitleOne(text: "msg_add_new_measurements".tr, margin: EdgeInsets.only(left: 40.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgEdit, margin: EdgeInsets.only(left: 16.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgThumbsUpGray90001, margin: EdgeInsets.only(left: 14.h, top: 20.v, right: 36.h))], styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildTabview() { return SizedBox(height: 40.v, width: 380.h, child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.gray90003, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Roboto', fontWeight: FontWeight.w500), unselectedLabelColor: appTheme.gray800, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Roboto', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: theme.colorScheme.onErrorContainer, borderRadius: BorderRadius.circular(8.h)), tabs: [Tab(child: Text("lbl_upper_body".tr)), Tab(child: Text("lbl_middle_body".tr)), Tab(child: Text("lbl_lower_body".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
