import 'controller/restoreserviceprovider_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/presentation/productscreen_container_page/productscreen_container_page.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/appbar_trailing_image.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_bottom_bar.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_icon_button.dart';class RestoreserviceproviderScreen extends GetWidget<RestoreserviceproviderController> {const RestoreserviceproviderScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: 412.h, child: Column(children: [SizedBox(height: 16.v), Expanded(child: SingleChildScrollView(child: Column(children: [_buildFilterOptions(), SizedBox(height: 16.v), _buildHeaderSection(), SizedBox(height: 16.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 15.v), decoration: AppDecoration.fillGray5001, child: Column(children: [_buildServiceProviderOne(), SizedBox(height: 16.v), _buildServiceProviderTwo(), SizedBox(height: 16.v), _buildServiceProviderFive()]))])))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgLinkedin, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v)), title: AppbarSubtitleFour(text: "lbl_koramangala".tr, margin: EdgeInsets.only(left: 16.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgSearchBlack900, margin: EdgeInsets.only(left: 16.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgNotification, margin: EdgeInsets.only(left: 28.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgLock, margin: EdgeInsets.only(left: 28.h, top: 20.v, right: 36.h))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFilterOptions() { return Padding(padding: EdgeInsets.only(left: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.fillOnErrorContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: SingleChildScrollView(scrollDirection: Axis.horizontal, padding: EdgeInsets.only(left: 8.h), child: IntrinsicWidth(child: Container(width: 92.h, decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgCheckmark, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_nearest".tr, style: CustomTextStyles.titleSmallGray90003)), Spacer(), Text("lbl_popular".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallGray800)]))))), Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 5.v), decoration: AppDecoration.outlineGray6001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgSignal, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_rating_4_0".tr, style: CustomTextStyles.titleSmallGray800))]))), Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 6.v), decoration: AppDecoration.outlineGray6001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpDeepPurple500, height: 18.adaptSize, width: 18.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_discounts".tr, style: CustomTextStyles.titleSmallGray800))]))), Container(height: 32.v, width: 35.h, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 6.v), decoration: AppDecoration.outlineGray6001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgLeadingIcon, height: 18.adaptSize, width: 18.adaptSize, alignment: Alignment.centerLeft))])); } 
/// Section Widget
Widget _buildHeaderSection() { return SizedBox(height: 20.v, width: 380.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 380.h, child: Divider(color: appTheme.gray90002))), Align(alignment: Alignment.center, child: Container(width: 184.h, padding: EdgeInsets.symmetric(horizontal: 8.h), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("msg_42_restore_services".tr, style: CustomTextStyles.bodyMedium_1)))])); } 
/// Section Widget
Widget _buildServiceProviderOne() { return GestureDetector(onTap: () {onTapServiceProviderOne();}, child: Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildServiceProviderFour(userImage: ImageConstant.imgFrame180x380), SizedBox(height: 15.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: _buildFrame(serviceProviderName: "msg_service_provider".tr, price: "msg_price_range_100_200".tr)), CustomElevatedButton(height: 28.v, width: 56.h, text: "lbl_4_3".tr, margin: EdgeInsets.only(bottom: 20.v), rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgSignalGray5001, height: 13.v, width: 12.h)), buttonStyle: CustomButtonStyles.fillTeal, buttonTextStyle: CustomTextStyles.titleSmallCabinGray50)])), SizedBox(height: 15.v)]))); } 
/// Section Widget
Widget _buildServiceProviderTwo() { return Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildServiceProviderFour(userImage: ImageConstant.imgFrame128), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_service_provider".tr, style: CustomTextStyles.titleMediumGray90002), SizedBox(height: 8.v), Text("msg_price_range_250_550".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 3.v), CustomImageView(imagePath: ImageConstant.imgTelevisionOrangeA100, height: 24.v, width: 84.h)])), CustomElevatedButton(height: 28.v, width: 56.h, text: "lbl_4_3".tr, margin: EdgeInsets.only(bottom: 48.v), rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgSignalGray5001, height: 13.v, width: 12.h)), buttonStyle: CustomButtonStyles.fillTeal, buttonTextStyle: CustomTextStyles.titleSmallCabinGray50)])), SizedBox(height: 16.v)])); } 
/// Section Widget
Widget _buildServiceProviderFive() { return SizedBox(height: 294.v, width: 380.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Text("lbl_end_of_page".tr.toUpperCase(), style: CustomTextStyles.bodySmallInterGray700)), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildServiceProviderFour(userImage: ImageConstant.imgFrame180x380), SizedBox(height: 15.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: _buildFrame(serviceProviderName: "msg_service_provider".tr, price: "msg_price_range_250_550".tr)), CustomElevatedButton(height: 28.v, width: 56.h, text: "lbl_4_3".tr, margin: EdgeInsets.only(bottom: 24.v), rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgSignalGray5001, height: 13.v, width: 12.h)), buttonStyle: CustomButtonStyles.fillTeal, buttonTextStyle: CustomTextStyles.titleSmallCabinGray50)])), SizedBox(height: 15.v)])), SizedBox(height: 22.v), SizedBox(width: 138.h, child: Divider(color: appTheme.gray700, indent: 38.h)), Align(alignment: Alignment.centerRight, child: SizedBox(width: 138.h, child: Divider(color: appTheme.gray700, endIndent: 38.h)))]))])); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
/// Common widget
Widget _buildServiceProviderFour({required String userImage}) { return SizedBox(height: 180.v, width: 380.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: userImage, height: 180.v, width: 380.h, radius: BorderRadius.vertical(top: Radius.circular(4.h)), alignment: Alignment.center), Padding(padding: EdgeInsets.only(top: 16.v, right: 16.h), child: CustomIconButton(height: 36.adaptSize, width: 36.adaptSize, padding: EdgeInsets.all(8.h), alignment: Alignment.topRight, child: CustomImageView(imagePath: ImageConstant.imgWishlistPro)))])); } 
/// Common widget
Widget _buildFrame({required String serviceProviderName, required String price, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(serviceProviderName, style: CustomTextStyles.titleMediumGray90002.copyWith(color: appTheme.gray90002)), SizedBox(height: 12.v), Text(price, style: CustomTextStyles.bodyMedium_1.copyWith(color: appTheme.gray90002))]); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.productscreenContainerPage; case BottomBarEnum.Quote: return "/"; case BottomBarEnum.Orders: return "/"; case BottomBarEnum.Replies: return "/"; case BottomBarEnum.Cart: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.productscreenContainerPage: return ProductscreenContainerPage(); default: return DefaultWidget();} } 
/// Navigates to the restoreServicesProviderProfileScreen when the action is triggered.
onTapServiceProviderOne() { Get.toNamed(AppRoutes.restoreServicesProviderProfileScreen, ); } 
 }
