import 'controller/profile_details_edit_controller.dart';import 'package:flutter/material.dart';import 'package:flutter_switch/flutter_switch.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';
// ignore_for_file: must_be_immutable
class ProfileDetailsEditScreen extends GetWidget<ProfileDetailsEditController> {ProfileDetailsEditScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 10.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgAvatar120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h)), SizedBox(height: 25.v), _buildFrame(label: "lbl_first_name".tr, text: "lbl_first_name2".tr, label1: "lbl_last_name".tr, text1: "lbl_last_name2".tr), SizedBox(height: 25.v), _buildInputWithLabelAlternativeMobile(), SizedBox(height: 25.v), _buildInputWithLabelAlternativeMobile(), SizedBox(height: 25.v), _buildInputWithLabelEmail(), SizedBox(height: 25.v), _buildInputWithLabelAlternativeMobile(), SizedBox(height: 25.v), _buildFrame(label: "lbl_city".tr, text: "lbl_bangalore".tr, label1: "lbl_pincode".tr, text1: "lbl_560069".tr), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 3.v), child: Text("msg_use_this_address".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => FlutterSwitch(value: controller.isSelectedSwitch.value, height: 24.h, width: 44.h, toggleSize: 20, borderRadius: 12.h, activeColor: appTheme.red200, activeToggleColor: appTheme.whiteA70001, inactiveColor: appTheme.blueGray50, inactiveToggleColor: appTheme.whiteA70001, onToggle: (value) {controller.isSelectedSwitch.value = value;})))])), SizedBox(height: 25.v), _buildInputWithLabelAlternativeMobile(), SizedBox(height: 25.v), _buildFrame(label: "lbl_city".tr, text: "lbl_bangalore".tr, label1: "lbl_pincode".tr, text1: "lbl_560069".tr), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 3.v), child: Text("msg_use_this_address".tr, style: theme.textTheme.labelLarge)), Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => FlutterSwitch(value: controller.isSelectedSwitch1.value, height: 24.h, width: 44.h, toggleSize: 20, borderRadius: 12.h, activeColor: appTheme.red200, activeToggleColor: appTheme.whiteA70001, inactiveColor: appTheme.blueGray50, inactiveToggleColor: appTheme.whiteA70001, onToggle: (value) {controller.isSelectedSwitch1.value = value;})))])), SizedBox(height: 33.v), Container(padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 11.v), width: SizeUtils.width, decoration: BoxDecoration(color: theme.colorScheme.onPrimary, borderRadius: BorderRadius.circular(8.h)), child: Text("lbl_edit2".tr, style: CustomTextStyles.titleSmallWhiteA70001)), SizedBox(height: 26.v), SizedBox(width: 108.h, child: Divider(height: 4.v, thickness: 4.v, color: appTheme.gray90004))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "lbl_profile".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildInputWithLabelEmail() { return Column(crossAxisAlignment: CrossAxisAlignment.center, children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_e_mail2".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 8.v), Align(alignment: Alignment.centerLeft, child: Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 12.v), decoration: AppDecoration.outlineGray900051.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Obx(() => Text(controller.profileDetailsEditModelObj.value.text1234.value, style: CustomTextStyles.bodyLargeSFProGray900))))]); } 
/// Common widget
Widget _buildInputWithLabelAlternativeMobile() { return Column(crossAxisAlignment: CrossAxisAlignment.center, children: [Align(alignment: Alignment.centerLeft, child: Text("msg_alternative_mobile".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 8.v), Align(alignment: Alignment.centerLeft, child: Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 12.v), decoration: AppDecoration.outlineGray900051.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_91_97894_56497".tr, style: CustomTextStyles.bodyLargeSFProGray900)))]); } 
/// Common widget
Widget _buildFrame({required String label, required String text, required String label1, required String text1, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 1.v, right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(label, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray90005)), SizedBox(height: 7.v), Container(width: 174.h, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 12.v), decoration: AppDecoration.outlineGray900051.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text(text, style: CustomTextStyles.bodyLargeSFProGray900.copyWith(color: appTheme.gray90002)))]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(label1, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray90005)), SizedBox(height: 8.v), Container(width: 174.h, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 12.v), decoration: AppDecoration.outlineGray900051.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text(text1, style: CustomTextStyles.bodyLargeSFProGray900.copyWith(color: appTheme.gray90002)))])))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
