import 'controller/profile_details_save_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/core/utils/validation_functions.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';import 'package:mykanji/widgets/custom_switch.dart';import 'package:mykanji/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class ProfileDetailsSaveScreen extends GetWidget<ProfileDetailsSaveController> {ProfileDetailsSaveScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 10.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgAvatar120x120, height: 120.adaptSize, width: 120.adaptSize, radius: BorderRadius.circular(60.h)), SizedBox(height: 25.v), _buildFrame(), SizedBox(height: 25.v), _buildInputWithLabelMobileNumber(), SizedBox(height: 25.v), _buildInputWithLabelAlternativeMobil(), SizedBox(height: 25.v), _buildInputWithLabelEmail(), SizedBox(height: 25.v), _buildInputWithLabelAddress(), SizedBox(height: 25.v), _buildFrame1(), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 3.v), child: Text("msg_use_this_address".tr, style: theme.textTheme.labelLarge)), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 24.h), value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))])), SizedBox(height: 25.v), _buildInputWithLabelAddressTwo(), SizedBox(height: 25.v), _buildFrame2(), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 3.v), child: Text("msg_use_this_address".tr, style: theme.textTheme.labelLarge)), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 24.h), value: controller.isSelectedSwitch1.value, onChange: (value) {controller.isSelectedSwitch1.value = value;}))])), SizedBox(height: 33.v), CustomElevatedButton(text: "lbl_save_changes".tr, buttonStyle: CustomButtonStyles.fillOnPrimary, buttonTextStyle: CustomTextStyles.titleSmallWhiteA70001), SizedBox(height: 26.v), SizedBox(width: 108.h, child: Divider())])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "lbl_profile".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildInputWithLabelFirstName() { return Expanded(child: Padding(padding: EdgeInsets.only(right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_first_name".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(width: 174.h, controller: controller.firstNameController, hintText: "lbl_first_name2".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]))); } 
/// Section Widget
Widget _buildInputWithLabelLastName() { return Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_last_name".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(width: 174.h, controller: controller.lastNameController, hintText: "lbl_last_name2".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]))); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildInputWithLabelFirstName(), _buildInputWithLabelLastName()]); } 
/// Section Widget
Widget _buildInputWithLabelMobileNumber() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_mobile_number".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(controller: controller.mobileNumberController, hintText: "lbl_91_96489_56845".tr, hintStyle: CustomTextStyles.bodyLargeSFProGray90005, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]); } 
/// Section Widget
Widget _buildInputWithLabelAlternativeMobil() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_alternative_mobile".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(controller: controller.mobileNumberController1, hintText: "lbl_91_97894_56497".tr, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]); } 
/// Section Widget
Widget _buildInputWithLabelEmail() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_e_mail2".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(controller: controller.emailController, hintText: "msg_enter_the_your_e_mail".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]); } 
/// Section Widget
Widget _buildInputWithLabelAddress() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_address_1".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(controller: controller.addressController, hintText: "msg_enter_the_your_address".tr, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]); } 
/// Section Widget
Widget _buildInputWithLabelCity() { return Expanded(child: Padding(padding: EdgeInsets.only(top: 1.v, right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), CustomTextFormField(width: 174.h, controller: controller.cityController, hintText: "lbl_bangalore".tr, hintStyle: CustomTextStyles.bodyLargeSFProGray90002, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]))); } 
/// Section Widget
Widget _buildInputWithLabelPincode() { return Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_pincode".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(width: 174.h, controller: controller.pincodeController, hintText: "lbl_560069".tr, hintStyle: CustomTextStyles.bodyLargeSFProGray90002, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]))); } 
/// Section Widget
Widget _buildFrame1() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildInputWithLabelCity(), _buildInputWithLabelPincode()]); } 
/// Section Widget
Widget _buildInputWithLabelAddressTwo() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_address_2".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(controller: controller.addressController1, hintText: "msg_enter_the_your_address".tr, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]); } 
/// Section Widget
Widget _buildInputWithLabelCity2() { return Expanded(child: Padding(padding: EdgeInsets.only(top: 1.v, right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_city".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), CustomTextFormField(width: 174.h, controller: controller.cityController1, hintText: "lbl_bangalore".tr, hintStyle: CustomTextStyles.bodyLargeSFProGray90002, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]))); } 
/// Section Widget
Widget _buildInputWithLabelPincodeTwo() { return Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_pincode".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), CustomTextFormField(width: 174.h, controller: controller.pincodeController1, hintText: "lbl_560069".tr, hintStyle: CustomTextStyles.bodyLargeSFProGray90002, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.outlineGrayTL81)]))); } 
/// Section Widget
Widget _buildFrame2() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildInputWithLabelCity2(), _buildInputWithLabelPincodeTwo()]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
