import 'controller/mymeasurment_controller.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_one.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';import 'package:mykanji/widgets/custom_elevated_button.dart';class MymeasurmentScreen extends GetWidget<MymeasurmentController> {const MymeasurmentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: 412.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v), child: Column(children: [SizedBox(height: 6.v), _buildMyMeasurementFrame(), Spacer(), CustomElevatedButton(text: "msg_add_new_measurements".tr, buttonStyle: CustomButtonStyles.fillOnPrimary, buttonTextStyle: CustomTextStyles.titleSmallWhiteA70001), SizedBox(height: 26.v), SizedBox(width: 108.h, child: Divider())])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_my_measurements".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildMyMeasurementFrame() { return GestureDetector(onTap: () {onTapMyMeasurementFrame();}, child: Container(padding: EdgeInsets.symmetric(horizontal: 2.h, vertical: 16.v), decoration: AppDecoration.fillGray90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLockGray80001, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, bottom: 3.v), child: Text("lbl_measurements_1".tr, style: CustomTextStyles.bodyLargeGray900))])), SizedBox(height: 16.v), Divider(color: appTheme.blueGray100)]), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLockGray80001, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, bottom: 3.v), child: Text("lbl_measurements_2".tr, style: CustomTextStyles.bodyLargeGray900))]))]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the upperBodyTabContainerScreen when the action is triggered.
onTapMyMeasurementFrame() { Get.toNamed(AppRoutes.upperBodyTabContainerScreen, ); } 
 }
