import '../profile_screen/widgets/listitemlistitem1_item_widget.dart';import 'controller/profile_controller.dart';import 'models/listitemlistitem1_item_model.dart';import 'package:flutter/material.dart';import 'package:mykanji/core/app_export.dart';import 'package:mykanji/widgets/app_bar/appbar_leading_image.dart';import 'package:mykanji/widgets/app_bar/appbar_subtitle_four.dart';import 'package:mykanji/widgets/app_bar/custom_app_bar.dart';class ProfileScreen extends GetWidget<ProfileController> {const ProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: 412.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 10.v), child: Column(children: [SizedBox(height: 6.v), _buildFrame(), SizedBox(height: 16.v), _buildListItemListItem(), SizedBox(height: 16.v), _buildFrame1(), SizedBox(height: 16.v), _buildListItem(), Spacer(), SizedBox(width: 108.h, child: Divider())])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 16.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleFour(text: "lbl_account".tr), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildFrame() { return GestureDetector(onTap: () {onTapFrame();}, child: Container(padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillDeeppurple50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgAvatar, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h)), Padding(padding: EdgeInsets.only(left: 24.h, top: 9.v, bottom: 9.v), child: Column(children: [Text("lbl_full_name".tr, style: theme.textTheme.titleLarge), SizedBox(height: 13.v), Text("lbl_9123456789".tr, style: theme.textTheme.titleMedium)]))]))); } 
/// Section Widget
Widget _buildListItemListItem() { return Container(padding: EdgeInsets.symmetric(horizontal: 10.h), decoration: AppDecoration.fillGray90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 14.v);}, itemCount: controller.profileModelObj.value.listitemlistitem1ItemList.value.length, itemBuilder: (context, index) {Listitemlistitem1ItemModel model = controller.profileModelObj.value.listitemlistitem1ItemList.value[index]; return Listitemlistitem1ItemWidget(model, onTapTxtWishlistText: () {onTapTxtWishlistText();});}))); } 
/// Section Widget
Widget _buildFrame1() { return Container(padding: EdgeInsets.symmetric(horizontal: 10.h), decoration: AppDecoration.fillGray90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgTermsAndCondition, height: 24.adaptSize, width: 24.adaptSize), GestureDetector(onTap: () {onTapTxtHeadline();}, child: Padding(padding: EdgeInsets.only(left: 16.h, bottom: 3.v), child: Text("msg_terms_and_condition".tr, style: CustomTextStyles.bodyLargeGray900)))]))), SizedBox(height: 16.v), Column(children: [Divider(color: appTheme.whiteA70001), SizedBox(height: 14.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgPrivacyPolicy, height: 24.adaptSize, width: 24.adaptSize), GestureDetector(onTap: () {onTapTxtHeadline1();}, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v), child: Text("lbl_privacy_policy".tr, style: CustomTextStyles.bodyLargeGray900)))])), SizedBox(height: 16.v), Divider(color: appTheme.whiteA70001)])]), SizedBox(height: 14.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgHelpSupport, height: 24.adaptSize, width: 24.adaptSize), GestureDetector(onTap: () {onTapTxtHeadline2();}, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v), child: Text("lbl_help_support".tr, style: CustomTextStyles.bodyLargeGray900)))])), SizedBox(height: 16.v), Divider(color: appTheme.blueGray100)])])); } 
/// Section Widget
Widget _buildListItem() { return Container(padding: EdgeInsets.symmetric(horizontal: 10.h), decoration: AppDecoration.fillGray90002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLogOut, height: 24.adaptSize, width: 24.adaptSize), GestureDetector(onTap: () {onTapTxtHeadline3();}, child: Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v), child: Text("lbl_logout".tr, style: CustomTextStyles.bodyLargeGray900)))])), SizedBox(height: 16.v), Divider(color: appTheme.blueGray100)])); } 
/// Navigates to the wishlistScreen when the action is triggered.
onTapTxtWishlistText() { Get.toNamed(AppRoutes.wishlistScreen); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the profileDetailsEditScreen when the action is triggered.
onTapFrame() { Get.toNamed(AppRoutes.profileDetailsEditScreen, ); } 
/// Navigates to the termsconditionScreen when the action is triggered.
onTapTxtHeadline() { Get.toNamed(AppRoutes.termsconditionScreen, ); } 
/// Navigates to the privacyPolicyScreen when the action is triggered.
onTapTxtHeadline1() { Get.toNamed(AppRoutes.privacyPolicyScreen, ); } 
/// Navigates to the helpAndSupportScreen when the action is triggered.
onTapTxtHeadline2() { Get.toNamed(AppRoutes.helpAndSupportScreen, ); } 
/// Navigates to the logintwoScreen when the action is triggered.
onTapTxtHeadline3() { Get.toNamed(AppRoutes.logintwoScreen, ); } 
 }
